.TH "accesstypes.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accesstypes.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBINSTFETCH\fP   0"
.br
.ti -1c
.RI "#define \fBDATALOAD\fP   1"
.br
.ti -1c
.RI "#define \fBDATASTORE\fP   2"
.br
.ti -1c
.RI "#define \fBANY\fP   3"
.br
.ti -1c
.RI "#define \fBMEM_READ\fP   0x01"
.br
.ti -1c
.RI "#define \fBMEM_WRITE\fP   0x02"
.br
.ti -1c
.RI "#define \fBMEM_READ_WRITE\fP   0x03"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ANY   3"
.SS "#define DATALOAD   1"
.SS "#define DATASTORE   2"
.SS "#define INSTFETCH   0"
.SS "#define MEM_READ   0x01"
.SS "#define MEM_READ_WRITE   0x03"
.SS "#define MEM_WRITE   0x02"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
