.TH "clockdev.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clockdev.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clock.h'\fP
.br
\fC#include 'deviceint.h'\fP
.br
\fC#include 'devicemap.h'\fP
.br
\fC#include 'devreg.h'\fP
.br
\fC#include 'task.h'\fP
.br
\fC#include <new>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClockDevice\fP"
.br
.ti -1c
.RI "class \fBClockDevice::ClockTrigger\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
