.TH "clockreg.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clockreg.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'devreg.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCDC_INTERRUPTS_ENABLED\fP   CTL_IE"
.br
.ti -1c
.RI "#define \fBCLOCK_BASE\fP   0x01010000"
.br
.ti -1c
.RI "#define \fBCLOCK_ADDR\fP   0xa1010000"
.br
.ti -1c
.RI "#define \fBREAL_SECONDS\fP   0x00"
.br
.ti -1c
.RI "#define \fBREAL_MICRO\fP   0x04"
.br
.ti -1c
.RI "#define \fBSIM_SECONDS\fP   0x08"
.br
.ti -1c
.RI "#define \fBSIM_MICRO\fP   0x0C"
.br
.ti -1c
.RI "#define \fBCLOCKDEV_CONTROL\fP   0x10"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CDC_INTERRUPTS_ENABLED   CTL_IE"
.SS "#define CLOCK_ADDR   0xa1010000"
.SS "#define CLOCK_BASE   0x01010000"
.SS "#define CLOCKDEV_CONTROL   0x10"
.SS "#define REAL_MICRO   0x04"
.SS "#define REAL_SECONDS   0x00"
.SS "#define SIM_MICRO   0x0C"
.SS "#define SIM_SECONDS   0x08"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
