.TH "coff_file_header" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coff_file_header \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBmagic\fP"
.br
.ti -1c
.RI "unsigned short \fBno_sections\fP"
.br
.ti -1c
.RI "char \fBextras\fP [20]"
.br
.ti -1c
.RI "unsigned long \fBtext_size\fP"
.br
.ti -1c
.RI "unsigned long \fBdata_size\fP"
.br
.ti -1c
.RI "unsigned long \fBbss_size\fP"
.br
.ti -1c
.RI "unsigned long \fBentry_addr\fP"
.br
.ti -1c
.RI "unsigned long \fBtext_start\fP"
.br
.ti -1c
.RI "unsigned long \fBdata_start\fP"
.br
.ti -1c
.RI "unsigned long \fBbss_start\fP"
.br
.ti -1c
.RI "char \fBextras2\fP [20]"
.br
.ti -1c
.RI "unsigned long \fBgp_value\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned long \fBcoff_file_header::bss_size\fP"
.SS "unsigned long \fBcoff_file_header::bss_start\fP"
.SS "unsigned long \fBcoff_file_header::data_size\fP"
.SS "unsigned long \fBcoff_file_header::data_start\fP"
.SS "unsigned long \fBcoff_file_header::entry_addr\fP"
.SS "char \fBcoff_file_header::extras\fP[20]"
.SS "char \fBcoff_file_header::extras2\fP[20]"
.SS "unsigned long \fBcoff_file_header::gp_value\fP"
.SS "unsigned short \fBcoff_file_header::magic\fP"
.SS "unsigned short \fBcoff_file_header::no_sections\fP"
.SS "unsigned long \fBcoff_file_header::text_size\fP"
.SS "unsigned long \fBcoff_file_header::text_start\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
