.TH "coff_section_header" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coff_section_header \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBsection_name\fP [8]"
.br
.ti -1c
.RI "unsigned long \fBsection_phys_addr\fP"
.br
.ti -1c
.RI "unsigned long \fBsection_virt_addr\fP"
.br
.ti -1c
.RI "unsigned long \fBsection_size\fP"
.br
.ti -1c
.RI "unsigned long \fBsection_file_loc\fP"
.br
.ti -1c
.RI "char \fBextras\fP [16]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char \fBcoff_section_header::extras\fP[16]"
.SS "unsigned long \fBcoff_section_header::section_file_loc\fP"
.SS "char \fBcoff_section_header::section_name\fP[8]"
.SS "unsigned long \fBcoff_section_header::section_phys_addr\fP"
.SS "unsigned long \fBcoff_section_header::section_size\fP"
.SS "unsigned long \fBcoff_section_header::section_virt_addr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
