.TH "coff_info" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coff_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcoff_file_header\fP \fBfile_header\fP"
.br
.ti -1c
.RI "unsigned long \fBtext_addr\fP"
.br
.ti -1c
.RI "unsigned long \fBtext_offset\fP"
.br
.ti -1c
.RI "unsigned long \fBtext_size\fP"
.br
.ti -1c
.RI "unsigned long \fBdata_addr\fP"
.br
.ti -1c
.RI "unsigned long \fBdata_offset\fP"
.br
.ti -1c
.RI "unsigned long \fBdata_size\fP"
.br
.ti -1c
.RI "unsigned long \fBbss_addr\fP"
.br
.ti -1c
.RI "unsigned long \fBbss_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned long \fBcoff_info::bss_addr\fP"
.SS "unsigned long \fBcoff_info::bss_size\fP"
.SS "unsigned long \fBcoff_info::data_addr\fP"
.SS "unsigned long \fBcoff_info::data_offset\fP"
.SS "unsigned long \fBcoff_info::data_size\fP"
.SS "struct \fBcoff_file_header\fP \fBcoff_info::file_header\fP"
.SS "unsigned long \fBcoff_info::text_addr\fP"
.SS "unsigned long \fBcoff_info::text_offset\fP"
.SS "unsigned long \fBcoff_info::text_size\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
