.TH "CponeClientData" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CponeClientData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prophetstatistic.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16 \fBm_rs\fP"
.br
.ti -1c
.RI "uint16 \fBm_funct\fP"
.br
.ti -1c
.RI "uint16 \fBm_ft\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint16 \fBCponeClientData::m_ft\fP"
.SS "uint16 \fBCponeClientData::m_funct\fP"
.SS "uint16 \fBCponeClientData::m_rs\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
