.TH "cpzero.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpzero.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tlbentry.h'\fP
.br
\fC#include <cstdio>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCPZero\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTLB_ENTRIES\fP   64"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define TLB_ENTRIES   64"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
