.TH "deccsrreg.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deccsrreg.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDECCSR_BASE\fP   0x1ff00000"
.br
.ti -1c
.RI "#define \fBCSR_RSRVD\fP   0xf0000000"
.br
.ti -1c
.RI "#define \fBCSR_PSWARN\fP   0x08000000"
.br
.ti -1c
.RI "#define \fBCSR_PRSVNVR\fP   0x04000000"
.br
.ti -1c
.RI "#define \fBCSR_REFEVEN\fP   0x02000000"
.br
.ti -1c
.RI "#define \fBCSR_NRMMOD\fP   0x01000000"
.br
.ti -1c
.RI "#define \fBCSR_IOINTEN\fP   0x00ff0000"
.br
.ti -1c
.RI "#define \fBCSR_ECCMD\fP   0x0000c000"
.br
.ti -1c
.RI "#define \fBCSR_CORRECT\fP   0x00002000"
.br
.ti -1c
.RI "#define \fBCSR_LEDIAG\fP   0x00001000"
.br
.ti -1c
.RI "#define \fBCSR_TXDIS\fP   0x00000800"
.br
.ti -1c
.RI "#define \fBCSR_BNK32M\fP   0x00000400"
.br
.ti -1c
.RI "#define \fBCSR_DIAGDN\fP   0x00000200"
.br
.ti -1c
.RI "#define \fBCSR_BAUD38\fP   0x00000100"
.br
.ti -1c
.RI "#define \fBCSR_RW_BITS\fP   0x00ffff00"
.br
.ti -1c
.RI "#define \fBCSR_IOINT\fP   0x000000ff"
.br
.ti -1c
.RI "#define \fBCSR_LEDS\fP   0x000000ff"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CSR_BAUD38   0x00000100"
.SS "#define CSR_BNK32M   0x00000400"
.SS "#define CSR_CORRECT   0x00002000"
.SS "#define CSR_DIAGDN   0x00000200"
.SS "#define CSR_ECCMD   0x0000c000"
.SS "#define CSR_IOINT   0x000000ff"
.SS "#define CSR_IOINTEN   0x00ff0000"
.SS "#define CSR_LEDIAG   0x00001000"
.SS "#define CSR_LEDS   0x000000ff"
.SS "#define CSR_NRMMOD   0x01000000"
.SS "#define CSR_PRSVNVR   0x04000000"
.SS "#define CSR_PSWARN   0x08000000"
.SS "#define CSR_REFEVEN   0x02000000"
.SS "#define CSR_RSRVD   0xf0000000"
.SS "#define CSR_RW_BITS   0x00ffff00"
.SS "#define CSR_TXDIS   0x00000800"
.SS "#define DECCSR_BASE   0x1ff00000"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
