.TH "decrtcreg.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decrtcreg.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDECRTC_BASE\fP   0x1fe80000"
.br
.ti -1c
.RI "#define \fBRTC_SEC\fP   0"
.br
.ti -1c
.RI "#define \fBRTC_ALMS\fP   1"
.br
.ti -1c
.RI "#define \fBRTC_MIN\fP   2"
.br
.ti -1c
.RI "#define \fBRTC_ALMM\fP   3"
.br
.ti -1c
.RI "#define \fBRTC_HOUR\fP   4"
.br
.ti -1c
.RI "#define \fBRTC_ALMH\fP   5"
.br
.ti -1c
.RI "#define \fBRTC_DOW\fP   6"
.br
.ti -1c
.RI "#define \fBRTC_DAY\fP   7"
.br
.ti -1c
.RI "#define \fBRTC_MON\fP   8"
.br
.ti -1c
.RI "#define \fBRTC_YEAR\fP   9"
.br
.ti -1c
.RI "#define \fBRTC_REGA\fP   10"
.br
.ti -1c
.RI "#define \fBRTC_REGB\fP   11"
.br
.ti -1c
.RI "#define \fBRTC_REGC\fP   12"
.br
.ti -1c
.RI "#define \fBRTC_REGD\fP   13"
.br
.ti -1c
.RI "#define \fBRTC_RAM\fP   14"
.br
.ti -1c
.RI "#define \fBREGA_UIP\fP   0x80"
.br
.ti -1c
.RI "#define \fBREGA_DVX\fP   0x70"
.br
.ti -1c
.RI "#define \fBREGA_RSX\fP   0x0f"
.br
.ti -1c
.RI "#define \fBREGB_SET\fP   0x80"
.br
.ti -1c
.RI "#define \fBREGB_PIE\fP   0x40"
.br
.ti -1c
.RI "#define \fBREGB_AIE\fP   0x20"
.br
.ti -1c
.RI "#define \fBREGB_UIE\fP   0x10"
.br
.ti -1c
.RI "#define \fBREGB_SQWE\fP   0x08"
.br
.ti -1c
.RI "#define \fBREGB_DM\fP   0x04"
.br
.ti -1c
.RI "#define \fBREGB_2412\fP   0x02"
.br
.ti -1c
.RI "#define \fBREGB_DSE\fP   0x01"
.br
.ti -1c
.RI "#define \fBREGC_IRQF\fP   0x80"
.br
.ti -1c
.RI "#define \fBREGC_PF\fP   0x40"
.br
.ti -1c
.RI "#define \fBREGC_AF\fP   0x20"
.br
.ti -1c
.RI "#define \fBREGC_UF\fP   0x10"
.br
.ti -1c
.RI "#define \fBREGC_RAZ\fP   0x0f"
.br
.ti -1c
.RI "#define \fBREGD_VRT\fP   0x80"
.br
.ti -1c
.RI "#define \fBREGD_RAZ\fP   0x7f"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DECRTC_BASE   0x1fe80000"
.SS "#define REGA_DVX   0x70"
.SS "#define REGA_RSX   0x0f"
.SS "#define REGA_UIP   0x80"
.SS "#define REGB_2412   0x02"
.SS "#define REGB_AIE   0x20"
.SS "#define REGB_DM   0x04"
.SS "#define REGB_DSE   0x01"
.SS "#define REGB_PIE   0x40"
.SS "#define REGB_SET   0x80"
.SS "#define REGB_SQWE   0x08"
.SS "#define REGB_UIE   0x10"
.SS "#define REGC_AF   0x20"
.SS "#define REGC_IRQF   0x80"
.SS "#define REGC_PF   0x40"
.SS "#define REGC_RAZ   0x0f"
.SS "#define REGC_UF   0x10"
.SS "#define REGD_RAZ   0x7f"
.SS "#define REGD_VRT   0x80"
.SS "#define RTC_ALMH   5"
.SS "#define RTC_ALMM   3"
.SS "#define RTC_ALMS   1"
.SS "#define RTC_DAY   7"
.SS "#define RTC_DOW   6"
.SS "#define RTC_HOUR   4"
.SS "#define RTC_MIN   2"
.SS "#define RTC_MON   8"
.SS "#define RTC_RAM   14"
.SS "#define RTC_REGA   10"
.SS "#define RTC_REGB   11"
.SS "#define RTC_REGC   12"
.SS "#define RTC_REGD   13"
.SS "#define RTC_SEC   0"
.SS "#define RTC_YEAR   9"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
