.TH "decstat.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decstat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'devicemap.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDECStatDevice\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDECSTAT_BASE\fP   0x1fd00000"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DECSTAT_BASE   0x1fd00000"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
