.TH "deviceint.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deviceint.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'intctrl.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeviceInt\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBIRQ7\fP   0x00008000"
.br
.ti -1c
.RI "#define \fBIRQ6\fP   0x00004000"
.br
.ti -1c
.RI "#define \fBIRQ5\fP   0x00002000"
.br
.ti -1c
.RI "#define \fBIRQ4\fP   0x00001000"
.br
.ti -1c
.RI "#define \fBIRQ3\fP   0x00000800"
.br
.ti -1c
.RI "#define \fBIRQ2\fP   0x00000400"
.br
.ti -1c
.RI "#define \fBIRQ1\fP   0x00000200"
.br
.ti -1c
.RI "#define \fBIRQ0\fP   0x00000100"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define IRQ0   0x00000100"
.SS "#define IRQ1   0x00000200"
.SS "#define IRQ2   0x00000400"
.SS "#define IRQ3   0x00000800"
.SS "#define IRQ4   0x00001000"
.SS "#define IRQ5   0x00002000"
.SS "#define IRQ6   0x00004000"
.SS "#define IRQ7   0x00008000"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
