.TH "deviceexc.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deviceexc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'accesstypes.h'\fP
.br
\fC#include 'types.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeviceExc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
