.TH "deviceint.cc" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deviceint.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'deviceint.h'\fP
.br
\fC#include 'options.h'\fP
.br
\fC#include 'vmips.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvmips\fP * \fBmachine\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBvmips\fP* \fBmachine\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
