.TH "devreg.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
devreg.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCTL_IE\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBCTL_RDY\fP   0x00000001"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CTL_IE   0x00000002"
.SS "#define CTL_RDY   0x00000001"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
