.TH "EndianSelfTester" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EndianSelfTester \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <endiantest.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEndianSelfTester\fP ()"
.br
.ti -1c
.RI "bool \fBhost_is_big_endian\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBhost_bigendian\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EndianSelfTester::EndianSelfTester ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "bool EndianSelfTester::host_is_big_endian () const\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "bool \fBEndianSelfTester::host_bigendian\fP\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
