.TH "excnames.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
excnames.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBInt\fP   0"
.br
.ti -1c
.RI "#define \fBMod\fP   1"
.br
.ti -1c
.RI "#define \fBTLBL\fP   2"
.br
.ti -1c
.RI "#define \fBTLBS\fP   3"
.br
.ti -1c
.RI "#define \fBAdEL\fP   4"
.br
.ti -1c
.RI "#define \fBAdES\fP   5"
.br
.ti -1c
.RI "#define \fBIBE\fP   6"
.br
.ti -1c
.RI "#define \fBDBE\fP   7"
.br
.ti -1c
.RI "#define \fBSys\fP   8"
.br
.ti -1c
.RI "#define \fBBp\fP   9"
.br
.ti -1c
.RI "#define \fBRI\fP   10"
.br
.ti -1c
.RI "#define \fBCpU\fP   11"
.br
.ti -1c
.RI "#define \fBOv\fP   12"
.br
.ti -1c
.RI "#define \fBTr\fP   13"
.br
.ti -1c
.RI "#define \fBNCD\fP   14"
.br
.ti -1c
.RI "#define \fBVCEI\fP   14"
.br
.ti -1c
.RI "#define \fBMV\fP   15"
.br
.ti -1c
.RI "#define \fBFPE\fP   15"
.br
.ti -1c
.RI "#define \fBWATCH\fP   23"
.br
.ti -1c
.RI "#define \fBVCED\fP   31"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define AdEL   4"
.SS "#define AdES   5"
.SS "#define Bp   9"
.SS "#define CpU   11"
.SS "#define DBE   7"
.SS "#define FPE   15"
.SS "#define IBE   6"
.SS "#define Int   0"
.SS "#define Mod   1"
.SS "#define MV   15"
.SS "#define NCD   14"
.SS "#define Ov   12"
.SS "#define RI   10"
.SS "#define Sys   8"
.SS "#define TLBL   2"
.SS "#define TLBS   3"
.SS "#define Tr   13"
.SS "#define VCED   31"
.SS "#define VCEI   14"
.SS "#define WATCH   23"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
