.TH "excPriority" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
excPriority \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpu.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "int \fBexcCode\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int \fBexcPriority::excCode\fP"
.SS "int \fBexcPriority::mode\fP"
.SS "int \fBexcPriority::priority\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
