.TH "fileutils.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fileutils.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcan_read_file\fP (char *filename)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool can_read_file (char * filename)"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
