.TH "gccattr.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gccattr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__ATTRIBUTE_FORMAT__\fP(archetype, string_index, first_to_check)"
.br
.ti -1c
.RI "#define \fB__ATTRIBUTE_NORETURN__\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define __ATTRIBUTE_FORMAT__(archetype, string_index, first_to_check)"
.SS "#define __ATTRIBUTE_NORETURN__"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
