.TH "haltreg.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
haltreg.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHALT_BASE\fP   0x01010024"
.br
.ti -1c
.RI "#define \fBHALT_ADDR\fP   0xa1010024"
.br
.ti -1c
.RI "#define \fBHALT_CONTROL\fP   0x00"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define HALT_ADDR   0xa1010024"
.SS "#define HALT_BASE   0x01010024"
.SS "#define HALT_CONTROL   0x00"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
