.TH "last_change" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
last_change \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpu.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlast_change\fP ()"
.br
.ti -1c
.RI "\fBlast_change\fP (uint32 pc_, uint32 instr_, uint32 old_value_)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBlast_change\fP \fBmake\fP (uint32 pc_, uint32 instr_, uint32 old_value_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32 \fBpc\fP"
.br
.ti -1c
.RI "uint32 \fBinstr\fP"
.br
.ti -1c
.RI "uint32 \fBold_value\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "last_change::last_change ()\fC [inline]\fP"
.SS "last_change::last_change (uint32 pc_, uint32 instr_, uint32 old_value_)\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "static \fBlast_change\fP last_change::make (uint32 pc_, uint32 instr_, uint32 old_value_)\fC [inline, static]\fP"
.SH "Member Data Documentation"
.PP 
.SS "uint32 \fBlast_change::instr\fP"
.SS "uint32 \fBlast_change::old_value\fP"
.SS "uint32 \fBlast_change::pc\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
