.TH "Mapper::BusErrorInfo" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mapper::BusErrorInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mapper.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalid\fP"
.br
.ti -1c
.RI "\fBDeviceExc\fP * \fBclient\fP"
.br
.ti -1c
.RI "int32 \fBmode\fP"
.br
.ti -1c
.RI "uint32 \fBaddr\fP"
.br
.ti -1c
.RI "int32 \fBwidth\fP"
.br
.ti -1c
.RI "uint32 \fBdata\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint32 \fBMapper::BusErrorInfo::addr\fP"
.SS "\fBDeviceExc\fP* \fBMapper::BusErrorInfo::client\fP"
.SS "uint32 \fBMapper::BusErrorInfo::data\fP"
.SS "int32 \fBMapper::BusErrorInfo::mode\fP"
.SS "bool \fBMapper::BusErrorInfo::valid\fP"
.SS "int32 \fBMapper::BusErrorInfo::width\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
