.TH "MemoryModule" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryModule \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memorymodule.h>\fP
.PP
Inherits \fBRange\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemoryModule\fP (size_t size)"
.br
.ti -1c
.RI "\fB~MemoryModule\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32 * \fBmyaddr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemoryModule::MemoryModule (size_t size)\fC [inline]\fP"
.SS "MemoryModule::~MemoryModule ()\fC [inline]\fP"
.SH "Member Data Documentation"
.PP 
.SS "uint32* \fBMemoryModule::myaddr\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
