.TH "options.cc" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
options.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'error.h'\fP
.br
\fC#include 'fileutils.h'\fP
.br
\fC#include 'options.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <cctype>\fP
.br
\fC#include <cerrno>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <pwd.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdlib.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBOPTBUFSIZ\fP   1024"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define OPTBUFSIZ   1024"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
