.TH "options.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
options.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBOptionValue\fP"
.br
.ti -1c
.RI "struct \fBOption\fP"
.br
.ti -1c
.RI "class \fBOptions\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSYSTEM_CONFIG_FILE\fP   '/home/qmwx/workspace/prophet_vmips_final_keyming_131130/vmipsrc'"
.br
.ti -1c
.RI "#define \fBTABLESIZE\fP   256"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBFLAG\fP =  1, \fBNUM\fP, \fBSTR\fP }"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define SYSTEM_CONFIG_FILE   '/home/qmwx/workspace/prophet_vmips_final_keyming_131130/vmipsrc'"
.SS "#define TABLESIZE   256"
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIFLAG \fP\fP
.TP
\fB\fINUM \fP\fP
.TP
\fB\fISTR \fP\fP

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
