.TH "Option" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Option \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union \fBOptionValue\fP \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* \fBOption::name\fP"
.SS "int \fBOption::type\fP"
.SS "union \fBOptionValue\fP \fBOption::value\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
