.TH "OptionValue" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionValue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBstr\fP"
.br
.ti -1c
.RI "bool \fBflag\fP"
.br
.ti -1c
.RI "uint32 \fBnum\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "bool \fBOptionValue::flag\fP"
.SS "uint32 \fBOptionValue::num\fP"
.SS "char* \fBOptionValue::str\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
