.TH "prophetcpustat.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophetcpustat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'prophetxmldoc.h'\fP
.br
\fC#include 'prophetxmlelement.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProphetStat::SquashOnSpList\fP"
.br
.ti -1c
.RI "class \fBProphetStat::ProphetCpuStat\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProphetStat\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBProphetStat::SquashOrSpawn\fP { \fBProphetStat::TOSQUASH\fP, \fBProphetStat::TOSPAWN\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
