.TH "prophetxmlelement.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophetxmlelement.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <deque>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXmlElement\fP"
.br
.RI "\fIA XML Element. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
