.TH "prophetsyscall.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophetsyscall.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPRINT_INT_SYSCALL\fP   1"
.br
.ti -1c
.RI "#define \fBPRINT_FLOAT_SYSCALL\fP   2"
.br
.ti -1c
.RI "#define \fBPRINT_DOUBLE_SYSCALL\fP   3"
.br
.ti -1c
.RI "#define \fBPRINT_STRING_SYSCALL\fP   4"
.br
.ti -1c
.RI "#define \fBPRINT_CHAR_SYSCALL\fP   5"
.br
.ti -1c
.RI "#define \fBREAD_INT_SYSCALL\fP   6"
.br
.ti -1c
.RI "#define \fBREAD_FLOAT_SYSCALL\fP   7"
.br
.ti -1c
.RI "#define \fBREAD_DOUBLE_SYSCALL\fP   8"
.br
.ti -1c
.RI "#define \fBREAD_STRING_SYSCALL\fP   9"
.br
.ti -1c
.RI "#define \fBREAD_CHAR_SYSCALL\fP   10"
.br
.ti -1c
.RI "#define \fBMALLOC_SYSCALL\fP   11"
.br
.ti -1c
.RI "#define \fBFREE_SYSCALL\fP   12"
.br
.ti -1c
.RI "#define \fBCLOSE_VERIFY\fP   13"
.br
.ti -1c
.RI "#define \fBOPEN_VERIFY\fP   14"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CLOSE_VERIFY   13"
.SS "#define FREE_SYSCALL   12"
.SS "#define MALLOC_SYSCALL   11"
.SS "#define OPEN_VERIFY   14"
.SS "#define PRINT_CHAR_SYSCALL   5"
.SS "#define PRINT_DOUBLE_SYSCALL   3"
.SS "#define PRINT_FLOAT_SYSCALL   2"
.SS "#define PRINT_INT_SYSCALL   1"
.SS "#define PRINT_STRING_SYSCALL   4"
.SS "#define READ_CHAR_SYSCALL   10"
.SS "#define READ_DOUBLE_SYSCALL   8"
.SS "#define READ_FLOAT_SYSCALL   7"
.SS "#define READ_INT_SYSCALL   6"
.SS "#define READ_STRING_SYSCALL   9"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
