.TH "prophetcpustat_test.cc" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophetcpustat_test.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prophetcpustat.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
