.TH "ProphetException" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProphetException \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <predefine.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProphetException\fP ()"
.br
.ti -1c
.RI "\fBProphetException\fP (std::string s)"
.br
.ti -1c
.RI "\fB~ProphetException\fP ()"
.br
.ti -1c
.RI "\fBGET_ACCESSOR\fP (std::string, Reason)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_Reason\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ProphetException::ProphetException ()\fC [inline]\fP"
.SS "ProphetException::ProphetException (std::string s)\fC [inline]\fP"
.SS "ProphetException::~ProphetException ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "ProphetException::GET_ACCESSOR (std::string, Reason)"
.SH "Member Data Documentation"
.PP 
.SS "std::string \fBProphetException::m_Reason\fP\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
