.TH "prophetxmldoc.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophetxmldoc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXmlDocument\fP"
.br
.RI "\fIA XML Document. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
