.TH "prophet_vmips.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophet_vmips.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'vmips.h'\fP
.br
\fC#include 'prophetlog.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProphet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
