.TH "prophetconsole.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophetconsole.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProphetConsole\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBProphetConsole::Init\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fBProphetConsole::Write\fP (const char *format,...)"
.br
.ti -1c
.RI "void \fBProphetConsole::Read\fP (char *buffer, int buflen)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
