.TH "prophetfpu.cc" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophetfpu.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prophetfpu.h'\fP
.br
\fC#include 'speculativecpu.h'\fP
.br
\fC#include 'deviceexc.h'\fP
.br
\fC#include 'intctrl.h'\fP
.br
\fC#include 'excnames.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFCSR\fP   31"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FCSR   31"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
