.TH "prophetfpu.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prophetfpu.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include 'types.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFPU\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBFPU_REG_NUMBER\fP   32"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define FPU_REG_NUMBER   32"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
