.TH "ROMModule" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ROMModule \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rommodule.h>\fP
.PP
Inherits \fBRange\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBROMModule\fP (FILE *f)"
.br
.ti -1c
.RI "virtual \fB~ROMModule\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ROMModule::ROMModule (FILE * f)"
.SS "ROMModule::~ROMModule ()\fC [virtual]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
