.TH "rommodule.cc" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rommodule.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'rommodule.h'\fP
.br
\fC#include 'range.h'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include 'vmips.h'\fP
.br
\fC#include <sys/mman.h>\fP
.br
\fC#include <cerrno>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
