.TH "SpawnClientData" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpawnClientData \- 
.PP
user defined data passed to its associated actions  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prophetstatistic.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProphetStat::RecAdder\fP * \fBm_SubAdder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
user defined data passed to its associated actions 
.SH "Member Data Documentation"
.PP 
.SS "\fBProphetStat::RecAdder\fP* \fBSpawnClientData::m_SubAdder\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
