.TH "spimconsole.cc" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spimconsole.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clock.h'\fP
.br
\fC#include 'mapper.h'\fP
.br
\fC#include 'spimconsole.h'\fP
.br
\fC#include 'deviceint.h'\fP
.br
\fC#include 'devicemap.h'\fP
.br
\fC#include 'task.h'\fP
.br
\fC#include 'terminalcontroller.h'\fP
.br
\fC#include <new>\fP
.br
\fC#include 'devreg.h'\fP
.br
\fC#include 'vmips.h'\fP
.br
\fC#include <cassert>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
