.TH "spimconsreg.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spimconsreg.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'devreg.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBSPIM_BASE\fP   0x02000000"
.br
.ti -1c
.RI "#define \fBSPIM_ADDR\fP   0xa2000000"
.br
.ti -1c
.RI "#define \fBKEYBOARD_1_CONTROL\fP   0x00"
.br
.ti -1c
.RI "#define \fBKEYBOARD_1_DATA\fP   0x04"
.br
.ti -1c
.RI "#define \fBDISPLAY_1_CONTROL\fP   0x08"
.br
.ti -1c
.RI "#define \fBDISPLAY_1_DATA\fP   0x0C"
.br
.ti -1c
.RI "#define \fBKEYBOARD_2_CONTROL\fP   0x10"
.br
.ti -1c
.RI "#define \fBKEYBOARD_2_DATA\fP   0x14"
.br
.ti -1c
.RI "#define \fBDISPLAY_2_CONTROL\fP   0x18"
.br
.ti -1c
.RI "#define \fBDISPLAY_2_DATA\fP   0x1C"
.br
.ti -1c
.RI "#define \fBCLOCK_CONTROL\fP   0x20"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CLOCK_CONTROL   0x20"
.SS "#define DISPLAY_1_CONTROL   0x08"
.SS "#define DISPLAY_1_DATA   0x0C"
.SS "#define DISPLAY_2_CONTROL   0x18"
.SS "#define DISPLAY_2_DATA   0x1C"
.SS "#define KEYBOARD_1_CONTROL   0x00"
.SS "#define KEYBOARD_1_DATA   0x04"
.SS "#define KEYBOARD_2_CONTROL   0x10"
.SS "#define KEYBOARD_2_DATA   0x14"
.SS "#define SPIM_ADDR   0xa2000000"
.SS "#define SPIM_BASE   0x02000000"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
