.TH "SpimConsoleDevice::ClockTrigger" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpimConsoleDevice::ClockTrigger \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spimconsole.h>\fP
.PP
Inherits \fBCancelableTask\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClockTrigger\fP (\fBSpimConsoleDevice\fP *\fBconsole\fP)  throw ()"
.br
.ti -1c
.RI "virtual \fB~ClockTrigger\fP ()  throw ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBreal_task\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSpimConsoleDevice\fP * \fBconsole\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpimConsoleDevice::ClockTrigger::ClockTrigger (\fBSpimConsoleDevice\fP * console)  throw ()"
.SS "SpimConsoleDevice::ClockTrigger::~ClockTrigger ()  throw ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void SpimConsoleDevice::ClockTrigger::real_task ()\fC [protected, virtual]\fP"
.PP
Implements \fBCancelableTask\fP.
.SH "Member Data Documentation"
.PP 
.SS "\fBSpimConsoleDevice\fP* \fBSpimConsoleDevice::ClockTrigger::console\fP\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
