.TH "SquashClientData" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SquashClientData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prophetstatistic.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBm_Reason\fP"
.br
.ti -1c
.RI "int \fBm_DisInSpList\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int \fBSquashClientData::m_DisInSpList\fP"
.SS "const char* \fBSquashClientData::m_Reason\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
