.TH "Task" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Task \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task.h>\fP
.PP
Inherited by \fBCancelableTask\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTask\fP ()  throw ()"
.br
.ti -1c
.RI "virtual \fB~Task\fP ()  throw ()"
.br
.ti -1c
.RI "virtual void \fBtask\fP ()=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Task::Task ()  throw ()\fC [inline]\fP"
.SS "virtual Task::~Task ()  throw ()\fC [inline, virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "virtual void Task::task ()\fC [pure virtual]\fP"
.PP
Implemented in \fBCancelableTask\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
