.TH "TerminalController::KeyboardPoll" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TerminalController::KeyboardPoll \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminalcontroller.h>\fP
.PP
Inherits \fBCancelableTask\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyboardPoll\fP (\fBTerminalController\fP *\fBcontroller\fP)  throw ()"
.br
.ti -1c
.RI "virtual \fB~KeyboardPoll\fP ()  throw ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBreal_task\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTerminalController\fP * \fBcontroller\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TerminalController::KeyboardPoll::KeyboardPoll (\fBTerminalController\fP * controller)  throw ()"
.SS "TerminalController::KeyboardPoll::~KeyboardPoll ()  throw ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void TerminalController::KeyboardPoll::real_task ()\fC [protected, virtual]\fP"
.PP
Implements \fBCancelableTask\fP.
.SH "Member Data Documentation"
.PP 
.SS "\fBTerminalController\fP* \fBTerminalController::KeyboardPoll::controller\fP\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
