.TH "TerminalController::LineState" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TerminalController::LineState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <terminalcontroller.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "termios \fBtty_state\fP"
.br
.ti -1c
.RI "int \fBtty_fd\fP"
.br
.ti -1c
.RI "\fBKeyboardRepoll\fP * \fBkeyboard_repoll\fP"
.br
.ti -1c
.RI "\fBDisplayDelay\fP * \fBdisplay_delay\fP"
.br
.ti -1c
.RI "char \fBkeyboard_char\fP"
.br
.ti -1c
.RI "\fBState\fP \fBkeyboard_state\fP"
.br
.ti -1c
.RI "\fBState\fP \fBdisplay_state\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBDisplayDelay\fP* \fBTerminalController::LineState::display_delay\fP"
.SS "\fBState\fP \fBTerminalController::LineState::display_state\fP"
.SS "char \fBTerminalController::LineState::keyboard_char\fP"
.SS "\fBKeyboardRepoll\fP* \fBTerminalController::LineState::keyboard_repoll\fP"
.SS "\fBState\fP \fBTerminalController::LineState::keyboard_state\fP"
.SS "int \fBTerminalController::LineState::tty_fd\fP"
.SS "termios \fBTerminalController::LineState::tty_state\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
