.TH "terminalcontroller.cc" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terminalcontroller.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clock.h'\fP
.br
\fC#include 'error.h'\fP
.br
\fC#include 'terminalcontroller.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <errno.h>\fP
.br
\fC#include <sys/time.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <string.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
