.TH "terminalcontroller.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
terminalcontroller.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'devreg.h'\fP
.br
\fC#include 'task.h'\fP
.br
\fC#include <new>\fP
.br
\fC#include <sys/types.h>\fP
.br
\fC#include <termios.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerminalController\fP"
.br
.ti -1c
.RI "class \fBTerminalController::DisplayDelay\fP"
.br
.ti -1c
.RI "class \fBTerminalController::KeyboardRepoll\fP"
.br
.ti -1c
.RI "class \fBTerminalController::KeyboardPoll\fP"
.br
.ti -1c
.RI "struct \fBTerminalController::LineState\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMAX_TERMINALS\fP   16"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define MAX_TERMINALS   16"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
