.TH "tlbentry.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlbentry.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config.h'\fP
.br
\fC#include 'cpzeroreg.h'\fP
.br
\fC#include 'types.h'\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTLBEntry\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
