.TH "wipe.h" 3 "18 Dec 2013" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wipe.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > void \fBwipe\fP (T x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class T > void wipe (T x)\fC [inline]\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
