XmlElement Class Reference
XmlElement Class Reference
A XML Element.
#include <prophetxmlelement.h>
Public Member Functions
XmlElement (std::string elementName, std::string content="")
Constructs an element with the specified name and string content.
XmlElement (std::string elementName, int numericContent)
Constructs an element with the specified name and numeric content.
virtual ~XmlElement ()
Destructs the element and its child elements.
std::string name () const
Returns the name of the element.
std::string content () const
Returns the content of the element.
void setName (const std::string &name)
Sets the name of the element.
void setContent (const std::string &content)
Sets the content of the element.
void setContent (int numericContent)
void addAttribute (std::string attributeName, std::string value)
Adds an attribute with the specified string value.
void addAttribute (std::string attributeName, int numericValue)
Adds an attribute with the specified numeric value.
void addElement (XmlElement *element)
Adds a child element to the element.
int elementCount () const
Returns the number of child elements.
XmlElement * elementAt (int index) const
Returns the child element at the specified index.
XmlElement * elementFor (const std::string &name) const
Returns the first child element with the specified name.
std::string toString (const std::string &indent="") const
Returns a XML string that represents the element.
Detailed Description
A XML Element.
A XML element has:
a name, specified on construction,
a content, specified on construction (may be empty),
zero or more attributes, added with addAttribute(),
zero or more child elements, added with addElement().
Definition at line 36 of file prophetxmlelement.h.
Constructor & Destructor Documentation
XmlElement::XmlElement (std::string elementName, std::string content = "")
Constructs an element with the specified name and string content.
Parameters:
elementName Name of the element. Must not be empty.
content Content of the element.
Definition at line 24 of file prophetxmlelement.cc.
XmlElement::XmlElement (std::string elementName, int numericContent)
Constructs an element with the specified name and numeric content.
Parameters:
elementName Name of the element. Must not be empty.
numericContent Content of the element.
Definition at line 29 of file prophetxmlelement.cc.
References setContent().
Member Function Documentation
void XmlElement::addAttribute (std::string attributeName, int numericValue)
Adds an attribute with the specified numeric value.
Parameters:
attributeName Name of the attribute. Must not be empty.
numericValue Numeric value of the attribute.
Definition at line 76 of file prophetxmlelement.cc.
References addAttribute().
void XmlElement::addAttribute (std::string attributeName, std::string value)
Adds an attribute with the specified string value.
Parameters:
attributeName Name of the attribute. Must not be an empty.
value Value of the attribute.
Definition at line 71 of file prophetxmlelement.cc.
Referenced by addAttribute().
void XmlElement::addElement (XmlElement * element)
Adds a child element to the element.
Parameters:
element Child element to add. Must not be NULL.
Definition at line 87 of file prophetxmlelement.cc.
Referenced by ProphetStat::ProphetCpuStat::addProCpuStatToXml().
std::string XmlElement::content () const
Returns the content of the element.
Returns:
Content of the element.
Definition at line 49 of file prophetxmlelement.cc.
XmlElement * XmlElement::elementAt (int index) const
Returns the child element at the specified index.
Parameters:
index Zero based index of the element to return.
Returns:
Element at the specified index. Never NULL.
Exceptions:
std::invalid_argument if index < 0 or index >= elementCount().
Definition at line 97 of file prophetxmlelement.cc.
References elementCount().
int XmlElement::elementCount () const
Returns the number of child elements.
Returns:
Number of child elements (element added with addElement()).
Definition at line 92 of file prophetxmlelement.cc.
Referenced by elementAt().
XmlElement * XmlElement::elementFor (const std::string & name) const
Returns the first child element with the specified name.
Parameters:
name Name of the child element to return.
Returns:
First child element found which is named name.
Exceptions:
std::invalid_argument if there is no child element with the specified name.
Definition at line 105 of file prophetxmlelement.cc.
std::string XmlElement::name () const
Returns the name of the element.
Returns:
Name of the element.
Definition at line 44 of file prophetxmlelement.cc.
void XmlElement::setContent (const std::string & content)
Sets the content of the element.
Parameters:
content New content for the element.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 59 of file prophetxmlelement.cc.
Referenced by XmlElement().
void XmlElement::setName (const std::string & name)
Sets the name of the element.
Parameters:
name New name for the element.
Definition at line 54 of file prophetxmlelement.cc.
std::string XmlElement::toString (const std::string & indent = "") const
Returns a XML string that represents the element.
Parameters:
indent String of spaces representing the amount of 'indent'.
Returns:
XML string that represents the element, its attributes and its child elements.
Definition at line 117 of file prophetxmlelement.cc.
References toString().
Referenced by toString().
The documentation for this class was generated from the following files:
prophetxmlelement.h
prophetxmlelement.cc